# Generated by Django 6.0.4 on 2026-05-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('staff', 'Personal'), ('delivery', 'Repartidor'), ('customer', 'Cliente')], default='customer', max_length=20),
        ),
    ]
