# Generated by Django 6.0.4 on 2026-05-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='shift',
            field=models.CharField(choices=[('morning', 'Matutino'), ('evening', 'Vespertino')], default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('chef', 'Cocinero'), ('delivery', 'Repartidor'), ('customer', 'Cliente')], default='customer', max_length=20),
        ),
    ]
