# Generated by Django 6.0.4 on 2026-05-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_phone_number'),
        ('accounts', '0007_alter_user_phone_number_alter_user_role_customer'),
    ]

    operations = [
    ]
