# Generated by Django 6.0.4 on 2026-05-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_managers_alter_chef_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='shift',
            field=models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino')], default='Matutino', max_length=20),
        ),
    ]
