# Generated by Django 6.0.4 on 2026-05-22 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_chef_shift'),
        ('logistics', '0002_building_unique_buildign_per_delivery_area_and_more'),
        ('menu', '0006_productingredient_min_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'En preparación'), ('ready', 'Listo'), ('delivering', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia')], default='cash', max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('custom_location', models.CharField(blank=True, max_length=255, null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='logistics.classroom')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='accounts.delivery')),
                ('delivery_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_deliveries', to='logistics.deliveryarea')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_location', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.CharField(blank=True, max_length=120, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('action', models.CharField(choices=[('normal', 'Normal'), ('removed', 'Removido'), ('extra', 'Extra'), ('modified', 'Modificado')], default='normal', max_length=10)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_ingredients', to='menu.ingredient')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='orders.orderitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order_item', 'ingredient', 'action'), name='unique_order_item_ingredient_action')],
            },
        ),
    ]
