# Generated by Django 6.0.4 on 2026-05-16 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_user_managers_alter_chef_shift'),
        ('menu', '0005_ingredient_allows_extra_ingredient_allows_removal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='menu.product')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping_cart.shoppingcart')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('normal', 'Normal'), ('remover', 'Remover'), ('extra', 'Extra')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='menu.ingredient')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='shopping_cart.shoppingcartitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cart_item', 'ingredient', 'action'), name='unique_cart_item_ingredient_action')],
            },
        ),
    ]
