# Generated by Django 6.0.4 on 2026-05-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('name', 'delivery_area'), name='unique_buildign_per_delivery_area'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('name', 'building'), name='unique_classroom_per_building'),
        ),
    ]
