# Generated by Django 6.0.4 on 2026-04-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='products', through='menu.ProductIngredient', to='menu.ingredient'),
        ),
    ]
