# Generated by Django 6.0.4 on 2026-04-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_product_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='base_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
