# Generated by Django 6.0.4 on 2026-05-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_ingredient_base_quantity_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='unique_product_ingredient'),
        ),
    ]
