# Generated by Django 6.0.4 on 2026-05-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_productingredient_unique_product_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='allows_extra',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='allows_removal',
            field=models.BooleanField(default=True),
        ),
    ]
