# Generated by Django 6.0.4 on 2026-05-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_ingredient_allows_extra_ingredient_allows_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='min_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
